#pragma once

#include <BWAPI.h>

#include <string>
#include <vector>

// An opponent bot the test harness can play against. The registry is generated by bots/StardustBots.cmake from the
// built-in opponents and every bots/*/bot.cmake.
struct RegisteredBot
{
    std::string name;
    BWAPI::Race race;
    BWAPI::AIModule *(*create)();
};

const std::vector<RegisteredBot> &RegisteredBots();

// Looks a bot up by name, ignoring case; nullptr if there is none
const RegisteredBot *FindBot(const std::string &name);
