# Opponent bots for the test harness. Each registered bot gets a factory function, and the generated registry lets
# test/Bots.cpp play any of them by name (STARDUST_OPPONENT=<name>). See bots/README.md.

# Registers a bot whose library target already exists: HEADER declares its BWAPI::AIModule subclass and CREATE is
# the C++ expression that creates one. The target must make HEADER's directory a PUBLIC include directory.
function(stardust_register_bot)
    cmake_parse_arguments(BOT "" "NAME;RACE;TARGET;HEADER;CREATE" "" ${ARGN})
    foreach (required NAME RACE TARGET HEADER CREATE)
        if (NOT BOT_${required})
            message(FATAL_ERROR "stardust_register_bot: ${required} is required")
        endif ()
    endforeach ()
    if (NOT BOT_NAME MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
        message(FATAL_ERROR "Bot name '${BOT_NAME}' must be a C++ identifier (letters, digits and _)")
    endif ()
    if (NOT BOT_RACE MATCHES "^(Protoss|Terran|Zerg|Random)$")
        message(FATAL_ERROR "Bot ${BOT_NAME}: RACE must be Protoss, Terran, Zerg or Random, not '${BOT_RACE}'")
    endif ()
    get_property(registered GLOBAL PROPERTY STARDUST_BOT_NAMES)
    if (BOT_NAME IN_LIST registered)
        message(FATAL_ERROR "A bot named ${BOT_NAME} is already registered")
    endif ()

    # The factory is compiled into the bot's own library, against its own headers. Bots can define the same classes
    # (two Steamhammer versions both have UAlbertaBot::UAlbertaBotModule), and inside its library each factory only
    # sees its own bot.
    set(factory ${CMAKE_BINARY_DIR}/bots/BotFactory_${BOT_NAME}.cpp)
    file(CONFIGURE OUTPUT ${factory} CONTENT [[// Generated by bots/StardustBots.cmake - do not edit.
#include "@BOT_HEADER@"

BWAPI::AIModule *stardustCreateBot_@BOT_NAME@()
{
    return @BOT_CREATE@;
}
]] @ONLY)
    target_sources(${BOT_TARGET} PRIVATE ${factory})

    set_property(GLOBAL APPEND PROPERTY STARDUST_BOT_NAMES ${BOT_NAME})
    set_property(GLOBAL APPEND PROPERTY STARDUST_BOT_TARGETS ${BOT_TARGET})
    set_property(GLOBAL APPEND PROPERTY STARDUST_BOT_RACES ${BOT_RACE})
endfunction()

# Builds a bot from sources in the directory of the bot.cmake calling it, then registers it. SOURCES and EXCLUDE are
# globs and INCLUDE_DIRS directories, all relative to that directory. DATA_AI and DATA_READ are globs of files to
# copy into the test harness's bwapi-data/AI and bwapi-data/read folders, where bots look for their data.
# VCXPROJ takes the sources from a Visual Studio project instead (its ClCompile items), so only what the author
# builds is compiled; EXCLUDE still applies. MSVC_COMPAT builds a bot written for Windows: it gets a stand-in
# <windows.h> and the Microsoft C runtime functions from bots/compat.
function(stardust_bot)
    cmake_parse_arguments(BOT "MSVC_COMPAT" "NAME;RACE;HEADER;CREATE;CXX_STANDARD;VCXPROJ"
                          "SOURCES;EXCLUDE;INCLUDE_DIRS;DEFINITIONS;DATA_AI;DATA_READ" ${ARGN})
    if (NOT BOT_SOURCES AND NOT BOT_VCXPROJ)
        message(FATAL_ERROR "stardust_bot ${BOT_NAME}: SOURCES or VCXPROJ is required")
    endif ()

    set(bot_dir ${CMAKE_CURRENT_LIST_DIR})
    set(sources "")
    if (BOT_VCXPROJ)
        set(project ${bot_dir}/${BOT_VCXPROJ})
        get_filename_component(project_dir ${project} DIRECTORY)
        file(STRINGS ${project} items REGEX "<ClCompile Include=\"[^\"]+\"")
        foreach (item ${items})
            string(REGEX REPLACE ".*<ClCompile Include=\"([^\"]+)\".*" "\\1" source "${item}")
            string(REPLACE "\\" "/" source "${source}")
            get_filename_component(source ${project_dir}/${source} ABSOLUTE)
            list(APPEND sources ${source})
        endforeach ()
    endif ()
    set(globs "")
    foreach (pattern ${BOT_SOURCES})
        list(APPEND globs ${bot_dir}/${pattern})
    endforeach ()
    if (globs)
        file(GLOB_RECURSE globbed CONFIGURE_DEPENDS ${globs})
        list(APPEND sources ${globbed})
    endif ()
    foreach (pattern ${BOT_EXCLUDE})
        file(GLOB_RECURSE excluded ${bot_dir}/${pattern})
        if (excluded)
            list(REMOVE_ITEM sources ${excluded})
        endif ()
    endforeach ()
    if (NOT sources)
        message(FATAL_ERROR "stardust_bot ${BOT_NAME}: no sources match ${BOT_SOURCES} in ${bot_dir}")
    endif ()

    set(target bot_${BOT_NAME})
    add_library(${target} SHARED ${sources})
    target_link_libraries(${target} PUBLIC BWAPILIB)
    target_include_directories(${target} SYSTEM PUBLIC ${bot_dir})
    foreach (dir ${BOT_INCLUDE_DIRS})
        target_include_directories(${target} SYSTEM PUBLIC ${bot_dir}/${dir})
    endforeach ()
    if (BOT_DEFINITIONS)
        target_compile_definitions(${target} PRIVATE ${BOT_DEFINITIONS})
    endif ()
    if (BOT_CXX_STANDARD)
        set_target_properties(${target} PROPERTIES CXX_STANDARD ${BOT_CXX_STANDARD})
    endif ()

    if (BOT_MSVC_COMPAT)
        set(compat ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/compat)
        target_include_directories(${target} SYSTEM PRIVATE ${compat}/include)
        # MSVC parses templates only when they are instantiated, so Windows code often uses names declared later
        target_compile_options(${target} PRIVATE -include ${compat}/msvc_compat.h -fdelayed-template-parsing)
        target_compile_definitions(${target} PRIVATE NOMINMAX)
    endif ()

    # Third-party code: its warnings aren't ours to fix
    target_compile_options(${target} PRIVATE -w)

    foreach (kind AI READ)
        string(TOLOWER ${kind} folder)
        if (kind STREQUAL "AI")
            set(folder AI)
        endif ()
        foreach (pattern ${BOT_DATA_${kind}})
            file(GLOB data_files ${bot_dir}/${pattern})
            if (data_files)
                file(COPY ${data_files} DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/bwapi-data/${folder})
            endif ()
        endforeach ()
    endforeach ()

    stardust_register_bot(NAME ${BOT_NAME} RACE ${BOT_RACE} TARGET ${target} HEADER ${BOT_HEADER}
                          CREATE ${BOT_CREATE})
endfunction()

# Includes every bots/*/bot.cmake. A folder without one is skipped with a message, so half-copied bots don't break
# the build.
function(stardust_add_bot_folders bots_dir)
    file(GLOB entries LIST_DIRECTORIES true ${bots_dir}/*)
    foreach (entry ${entries})
        if (NOT IS_DIRECTORY ${entry})
            continue()
        endif ()
        get_filename_component(folder ${entry} NAME)
        if (EXISTS ${entry}/bot.cmake)
            include(${entry}/bot.cmake)
        elseif (NOT folder MATCHES "^(\\..*|compat|recipes)$")
            message(STATUS "bots/${folder} has no bot.cmake, skipping it (see bots/README.md)")
        endif ()
    endforeach ()
endfunction()

# Writes the registry of all registered bots to OUTPUT and sets STARDUST_BOT_LIBRARIES in the caller to the bot
# libraries to link.
function(stardust_write_bot_registry output)
    get_property(names GLOBAL PROPERTY STARDUST_BOT_NAMES)
    get_property(races GLOBAL PROPERTY STARDUST_BOT_RACES)
    get_property(targets GLOBAL PROPERTY STARDUST_BOT_TARGETS)

    set(declarations "")
    set(entries "")
    foreach (name race IN ZIP_LISTS names races)
        string(APPEND declarations "BWAPI::AIModule *stardustCreateBot_${name}();\n")
        string(APPEND entries "            {\"${name}\", BWAPI::Races::${race}, &stardustCreateBot_${name}},\n")
    endforeach ()

    file(CONFIGURE OUTPUT ${output} CONTENT [[// Generated by bots/StardustBots.cmake - do not edit.
#include "BotRegistry.h"

@declarations@
const std::vector<RegisteredBot> &RegisteredBots()
{
    static const std::vector<RegisteredBot> bots = {
@entries@    };
    return bots;
}
]] @ONLY)

    list(LENGTH names count)
    message(STATUS "Opponent bots (${count}): ${names}")
    set(STARDUST_BOT_LIBRARIES ${targets} PARENT_SCOPE)
endfunction()
