"""Port of Util/UnitUtil.{h,cpp}: unit type facts used throughout the bot."""

from functools import cache

from bwapi import Races, TilePosition, UnitType, UnitTypes, WeaponType, WeaponTypes

_WARP_IN_FRAMES = 71

# Indexed by weapon ID (_WEAPON_ANGLES) or unit type ID (the others). _HALT_DISTANCES are partly adjusted from
# observed behaviour; _ATTACK_FRAME_DELAYS (frames from going on cooldown until the bullet is created or damage is
# dealt) were generated by Stardust's UnitAttackTimings test.
_WEAPON_ANGLES = (
    16, 16, 16, 16, 64, 64, 128, 16, 32, 16, 32, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 128, 128, 128, 128, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 128, 128, 16, 16, 16, 16, 16, 16, 32, 16, 32, 16, 16, 16,
    128, 128, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 128, 128, 96, 64, 16, 32, 32, 32,
    16, 16, 16, 32, 16, 16, 16, 16, 16, 0, 16, 16, 16, 16, 16, 32, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 0, 0, 0, 0,
)

_HALT_DISTANCES = (
    0, 0, 57, 0, 0, 0, 0, 48, 85, 20,
    0, 147, 30, 0, 4309, 0, 0, 0, 0, 57,
    0, 85, 20, 0, 0, 0, 0, 30, 30, 30,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 48, 3, 85, 30, 85, 0, 53, 0, 85,
    0, 0, 0, 0, 0, 85, 30, 3, 86, 0,
    131, 53, 67, 20, 48, 0, 0, 53, 20, 147,
    67, 97, 53, 53, 53, 53, 20, 0, 0, 53,
    67, 0, 53, 0, 53, 0, 97, 53, 67, 0,
    0, 0, 0, 0, 200, 0, 0, 0, 67, 0,
    0, 0, 30, 0, 0, 0, 11, 0, 0, 0,
    11, 11, 0, 11, 11, 0, 11, 0, 0, 0,
    0, 0, 11, 0, 0, 11, 0, 0, 0, 0,
    11, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0,
)

_ATTACK_FRAME_DELAYS = (
    2, 2, 0, 0, 0, 2, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    2, 0, 0, 0, 0, 0, 0, 1, 4, 4,
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 4, 9, 0, 0, 3, 7, 0, 4, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 9, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 6, 0, 0, 0, 0, 0, 0, 0,
)


def powers(pylon_tile: TilePosition, building_tile: TilePosition, building_type: UnitType) -> bool:
    """Whether a pylon at pylon_tile powers a building of building_type at building_tile."""
    offset_y = building_tile.y - pylon_tile.y
    offset_x = building_tile.x - pylon_tile.x

    if building_type.tileWidth() == 4:
        if offset_y < -5 or offset_y > 4:
            return False
        if offset_y in (-5, 4) and (offset_x < -4 or offset_x > 1):
            return False
        if offset_y in (-4, 3) and (offset_x < -7 or offset_x > 4):
            return False
        if offset_y in (-3, 2) and (offset_x < -8 or offset_x > 5):
            return False
        return -8 <= offset_x <= 6

    if offset_y < -4 or offset_y > 4:
        return False
    if offset_y == 4 and (offset_x < -3 or offset_x > 2):
        return False
    if offset_y in (-4, 3) and (offset_x < -6 or offset_x > 5):
        return False
    if offset_y in (-3, 2) and (offset_x < -7 or offset_x > 6):
        return False
    if building_type.tileWidth() == 2:
        return -7 <= offset_x <= 7
    return -8 <= offset_x <= 7


@cache
def build_time(unit_type: UnitType) -> int:
    # TODO (upstream): Technically zerg and terran also have an animation that needs to play after finished construction
    if unit_type.getRace() == Races.Protoss and unit_type.isBuilding():
        return unit_type.buildTime() + _WARP_IN_FRAMES
    return unit_type.buildTime()


@cache
def get_ground_weapon(attacker: UnitType) -> WeaponType:
    # Assume bunkers have marines in them
    if attacker == UnitTypes.Terran_Bunker:
        return get_ground_weapon(UnitTypes.Terran_Marine)
    if attacker == UnitTypes.Protoss_Carrier:
        return get_ground_weapon(UnitTypes.Protoss_Interceptor)
    if attacker == UnitTypes.Protoss_Reaver:
        return get_ground_weapon(UnitTypes.Protoss_Scarab)
    return attacker.groundWeapon()


@cache
def get_air_weapon(attacker: UnitType) -> WeaponType:
    # Assume bunkers have marines in them
    if attacker == UnitTypes.Terran_Bunker:
        return get_air_weapon(UnitTypes.Terran_Marine)
    if attacker == UnitTypes.Protoss_Carrier:
        return get_air_weapon(UnitTypes.Protoss_Interceptor)
    return attacker.airWeapon()


@cache
def max_ground_hits(attacker: UnitType) -> int:
    # Assume bunkers have marines in them
    if attacker == UnitTypes.Terran_Bunker:
        return UnitTypes.Terran_Marine.maxGroundHits()
    if attacker == UnitTypes.Protoss_Carrier:
        return UnitTypes.Protoss_Interceptor.maxGroundHits()
    if attacker == UnitTypes.Protoss_Reaver:
        return UnitTypes.Protoss_Scarab.maxGroundHits()
    return attacker.maxGroundHits()


@cache
def max_air_hits(attacker: UnitType) -> int:
    # Assume bunkers have marines in them
    if attacker == UnitTypes.Terran_Bunker:
        return UnitTypes.Terran_Marine.maxAirHits()
    if attacker == UnitTypes.Protoss_Carrier:
        return UnitTypes.Protoss_Interceptor.maxAirHits()
    return attacker.maxAirHits()


@cache
def can_attack_ground(attacker_type: UnitType) -> bool:
    return (attacker_type.groundWeapon() != WeaponTypes.None_
            or attacker_type in (UnitTypes.Protoss_Carrier, UnitTypes.Protoss_Reaver,
                                 UnitTypes.Terran_Science_Vessel, UnitTypes.Terran_Bunker))


@cache
def can_attack_air(attacker_type: UnitType) -> bool:
    return (attacker_type.airWeapon() != WeaponTypes.None_
            or attacker_type in (UnitTypes.Protoss_Carrier, UnitTypes.Terran_Bunker))


@cache
def is_ranged_unit(unit_type: UnitType) -> bool:
    return (unit_type.groundWeapon().maxRange() > 32
            or unit_type.isFlyer()
            or unit_type == UnitTypes.Protoss_Reaver)


@cache
def is_combat_unit(unit_type: UnitType) -> bool:
    if is_stationary_attacker(unit_type):
        return True  # So we include static defense
    if unit_type.isWorker() or unit_type.isBuilding():
        return False
    return (unit_type.canAttack()
            or unit_type.isDetector()
            or unit_type in (UnitTypes.Zerg_Queen, UnitTypes.Zerg_Defiler, UnitTypes.Terran_Medic,
                             UnitTypes.Protoss_High_Templar, UnitTypes.Protoss_Dark_Archon)
            or (unit_type.isFlyer() and unit_type.spaceProvided() > 0))


@cache
def is_stationary_attacker(unit_type: UnitType) -> bool:
    """Whether the type typically remains in the same position as long as it can attack.

    Beyond static defense buildings, this includes sieged tanks and lurkers.
    """
    return unit_type in (UnitTypes.Protoss_Photon_Cannon, UnitTypes.Zerg_Sunken_Colony, UnitTypes.Zerg_Spore_Colony,
                         UnitTypes.Zerg_Lurker, UnitTypes.Terran_Missile_Turret, UnitTypes.Terran_Bunker,
                         UnitTypes.Terran_Siege_Tank_Siege_Mode)


@cache
def morphs_from(unit_type: UnitType) -> tuple[UnitType, int]:
    builder, count = unit_type.whatBuilds()

    # Anything built by a drone is a morph
    if builder == UnitTypes.Zerg_Drone:
        return builder, count

    # A building "built" by another building is a morph, unless it is an add-on
    if unit_type.isBuilding() and not unit_type.isAddon() and builder.isBuilding():
        return builder, count

    # A unit "built" by another unit is a morph unless it is an interceptor or scarab
    if (not unit_type.isBuilding() and not builder.isBuilding()
            and unit_type not in (UnitTypes.Protoss_Interceptor, UnitTypes.Protoss_Scarab)):
        return builder, count

    return UnitTypes.None_, 0


@cache
def mineral_cost(unit_type: UnitType) -> int:
    if unit_type in (UnitTypes.None_, UnitTypes.Unknown):
        return 0

    minerals = unit_type.mineralPrice()

    # BWAPI lists some units as having mineral cost 1 instead of 0, e.g. Larva
    if minerals == 1:
        minerals = 0

    if unit_type.isTwoUnitsInOneEgg():
        minerals //= 2

    builder, count = morphs_from(unit_type)
    if count > 0:
        minerals += count * mineral_cost(builder)

    return minerals


@cache
def gas_cost(unit_type: UnitType) -> int:
    if unit_type in (UnitTypes.None_, UnitTypes.Unknown, UnitTypes.Zerg_Larva):
        return 0

    gas = unit_type.gasPrice()

    # BWAPI lists some units as having gas cost 1 instead of 0, e.g. Larva
    if gas == 1:
        gas = 0

    if unit_type.isTwoUnitsInOneEgg():
        gas //= 2

    builder, count = morphs_from(unit_type)
    if count > 0:
        gas += count * gas_cost(builder)

    return gas


def ground_weapon_angle(unit_type: UnitType) -> int:
    weapon_id = unit_type.groundWeapon().getID()
    return _WEAPON_ANGLES[weapon_id] if weapon_id < len(_WEAPON_ANGLES) else 0


def air_weapon_angle(unit_type: UnitType) -> int:
    weapon_id = unit_type.airWeapon().getID()
    return _WEAPON_ANGLES[weapon_id] if weapon_id < len(_WEAPON_ANGLES) else 0


def halt_distance(unit_type: UnitType) -> int:
    type_id = unit_type.getID()
    return _HALT_DISTANCES[type_id] if type_id < len(_HALT_DISTANCES) else 0


def acceleration(unit_type: UnitType, current_top_speed: float) -> int:
    """Acceleration in BW notation (multiples of 1/256). Doubled when speed is upgraded."""
    if current_top_speed > unit_type.topSpeed():
        return unit_type.acceleration() << 1
    return unit_type.acceleration()


def delay_from_cooldown_to_bullet_or_damage(unit_type: UnitType) -> int:
    """Frames from the unit going on cooldown until the resulting bullet is created or damage is dealt."""
    type_id = unit_type.getID()
    return _ATTACK_FRAME_DELAYS[type_id] if type_id < len(_ATTACK_FRAME_DELAYS) else 0
