"""BWEM map analysis (areas, chokepoints, bases). Method names follow BWEM's C++ API.

All objects are owned by the map singleton and compare/hash by identity.
"""

from typing import ClassVar, overload

from bwapi import Position, TilePosition, Unit, UnitType, WalkPosition

class Area:
    def Id(self) -> int: ...
    def GroupId(self) -> int: ...
    def TopLeft(self) -> TilePosition: ...
    def BottomRight(self) -> TilePosition: ...
    def BoundingBoxSize(self) -> TilePosition: ...
    def Top(self) -> WalkPosition: ...
    def MaxAltitude(self) -> int: ...
    def MiniTiles(self) -> int: ...
    def LowGroundPercentage(self) -> int: ...
    def HighGroundPercentage(self) -> int: ...
    def VeryHighGroundPercentage(self) -> int: ...
    @overload
    def ChokePoints(self) -> list[ChokePoint]: ...
    @overload
    def ChokePoints(self, other: Area) -> list[ChokePoint]: ...
    def ChokePointsByArea(self) -> dict[Area, list[ChokePoint]]: ...
    def AccessibleNeighbours(self) -> list[Area]: ...
    def AccessibleFrom(self, other: Area) -> bool: ...
    def Minerals(self) -> list[Mineral]: ...
    def Geysers(self) -> list[Geyser]: ...
    def Bases(self) -> list[Base]: ...
    def __hash__(self) -> int: ...

class ChokePoint:
    class node:
        end1: ClassVar[ChokePoint.node]
        middle: ClassVar[ChokePoint.node]
        end2: ClassVar[ChokePoint.node]
        __members__: ClassVar[dict[str, ChokePoint.node]]
        def __init__(self, value: int) -> None: ...
        @property
        def name(self) -> str: ...
        @property
        def value(self) -> int: ...
        def __int__(self) -> int: ...
        def __index__(self) -> int: ...
    end1: ClassVar[ChokePoint.node]
    middle: ClassVar[ChokePoint.node]
    end2: ClassVar[ChokePoint.node]
    def GetAreas(self) -> tuple[Area, Area]: ...
    def Center(self) -> WalkPosition: ...
    def Pos(self, n: ChokePoint.node) -> WalkPosition: ...
    def PosInArea(self, n: ChokePoint.node, area: Area) -> WalkPosition: ...
    def Geometry(self) -> list[WalkPosition]: ...
    def Blocked(self) -> bool: ...
    def BlockingNeutral(self) -> Neutral | None: ...
    def DistanceFrom(self, other: ChokePoint) -> int: ...
    def AccessibleFrom(self, other: ChokePoint) -> bool: ...
    def Index(self) -> int: ...
    def __hash__(self) -> int: ...

class Base:
    def GetArea(self) -> Area: ...
    def Location(self) -> TilePosition: ...
    def Center(self) -> Position: ...
    def Minerals(self) -> list[Mineral]: ...
    def Geysers(self) -> list[Geyser]: ...
    def BlockingMinerals(self) -> list[Mineral]: ...
    def Starting(self) -> bool: ...
    def __hash__(self) -> int: ...

class Neutral:
    def Unit(self) -> Unit: ...
    def Type(self) -> UnitType: ...
    def Pos(self) -> Position: ...
    def TopLeft(self) -> TilePosition: ...
    def BottomRight(self) -> TilePosition: ...
    def Size(self) -> TilePosition: ...
    def BlockedAreas(self) -> list[Area]: ...
    def NextStacked(self) -> Neutral | None: ...
    def __hash__(self) -> int: ...

class Ressource(Neutral):
    def InitialAmount(self) -> int: ...
    def Amount(self) -> int: ...

class Mineral(Ressource): ...
class Geyser(Ressource): ...
class StaticBuilding(Neutral): ...

class MiniTile:
    def Walkable(self) -> bool: ...
    def Altitude(self) -> int: ...
    def Sea(self) -> bool: ...
    def Lake(self) -> bool: ...
    def Terrain(self) -> bool: ...
    def AreaId(self) -> int: ...
    def Blocked(self) -> bool: ...
    def __hash__(self) -> int: ...

class Tile:
    def Buildable(self) -> bool: ...
    def GroundHeight(self) -> int: ...
    def Doodad(self) -> bool: ...
    def AreaId(self) -> int: ...
    def MinAltitude(self) -> int: ...
    def GetNeutral(self) -> Neutral | None: ...
    def __hash__(self) -> int: ...

class Map:
    def Initialize(self) -> None:
        """Analyze the current game's map. Raises RuntimeError outside a game."""
    def EnableAutomaticPathAnalysis(self) -> None: ...
    def AutomaticPathUpdate(self) -> bool: ...
    def FindBasesForStartingLocations(self) -> bool: ...
    def Size(self) -> TilePosition: ...
    def WalkSize(self) -> WalkPosition: ...
    def Center(self) -> Position: ...
    def MaxAltitude(self) -> int: ...
    def BaseCount(self) -> int: ...
    def ChokePointCount(self) -> int: ...
    @overload
    def Valid(self, p: TilePosition) -> bool: ...
    @overload
    def Valid(self, p: WalkPosition) -> bool: ...
    @overload
    def Valid(self, p: Position) -> bool: ...
    def GetTile(self, p: TilePosition) -> Tile:
        """Raises IndexError for positions outside the map."""
    def GetMiniTile(self, p: WalkPosition) -> MiniTile:
        """Raises IndexError for positions outside the map."""
    def StartingLocations(self) -> list[TilePosition]: ...
    def Minerals(self) -> list[Mineral]: ...
    def Geysers(self) -> list[Geyser]: ...
    def StaticBuildings(self) -> list[StaticBuilding]: ...
    def GetMineral(self, unit: Unit) -> Mineral | None: ...
    def GetGeyser(self, unit: Unit) -> Geyser | None: ...
    def OnMineralDestroyed(self, unit: Unit) -> None: ...
    def OnStaticBuildingDestroyed(self, unit: Unit) -> None: ...
    def Areas(self) -> list[Area]: ...
    @overload
    def GetArea(self, id: int) -> Area | None: ...
    @overload
    def GetArea(self, w: WalkPosition) -> Area | None:
        """None for positions outside the map or in no area."""
    @overload
    def GetArea(self, t: TilePosition) -> Area | None: ...
    @overload
    def GetNearestArea(self, w: WalkPosition) -> Area | None: ...
    @overload
    def GetNearestArea(self, t: TilePosition) -> Area | None: ...
    def GetPath(self, a: Position, b: Position) -> tuple[list[ChokePoint], int]:
        """Chokepoints on the shortest ground path from a to b, and its length in pixels (-1 if unreachable)."""
    def __hash__(self) -> int: ...

def Instance() -> Map: ...
def ResetInstance() -> None: ...
