"""Generated by tools/gen_blocks.py from Stardust's Builder/Blocks/13x6.h; do not edit."""

from __future__ import annotations

import bwapi
from bwapi import TilePosition
from stardust.builder.block import Block, Location


class Block13x6(Block):
    def width(self) -> int:
        return 13

    def height(self) -> int:
        return 6

    def allow_top_edge(self) -> bool:
        return False

    def allow_corner(self) -> bool:
        return False

    def try_create(self, tile: TilePosition, tile_availability: list[int]) -> Block | None:
        if self.place(tile, tile_availability):
            if self.top_left.x + 17 < bwapi.Broodwar.mapWidth():
                return Block13x6(tile, tile + TilePosition(8, 2))
            else:
                return Block13x6(tile, tile + TilePosition(7, 2))
        return None

    def place_locations(self) -> None:
        if self.top_left.x + 17 < bwapi.Broodwar.mapWidth():
            self.small.append(Location(self.top_left + TilePosition(8, 2)))
            self.small.append(Location(self.top_left + TilePosition(8, 0)))
            self.small.append(Location(self.top_left + TilePosition(8, 4)))
            self.large.append(Location(self.top_left))
            self.large.append(Location(self.top_left + TilePosition(0, 3)))
            self.large.append(Location(self.top_left + TilePosition(4, 0)))
            self.large.append(Location(self.top_left + TilePosition(4, 3)))
            self.medium.append(Location(self.top_left + TilePosition(10, 0)))
            self.medium.append(Location(self.top_left + TilePosition(10, 2)))
            self.medium.append(Location(self.top_left + TilePosition(10, 4)))
            self.medium.append(Location(self.top_left + TilePosition(1, 1), True))
            self.medium.append(Location(self.top_left + TilePosition(1, 3), True))
            self.medium.append(Location(self.top_left + TilePosition(5, 1), True))
            self.medium.append(Location(self.top_left + TilePosition(5, 3), True))
            self.small.append(Location(self.top_left + TilePosition(0, 1), True))
            self.small.append(Location(self.top_left + TilePosition(2, 1), True))
            self.small.append(Location(self.top_left + TilePosition(0, 3), True))
            self.small.append(Location(self.top_left + TilePosition(2, 3), True))
            self.small.append(Location(self.top_left + TilePosition(4, 1), True))
            self.small.append(Location(self.top_left + TilePosition(6, 1), True))
            self.small.append(Location(self.top_left + TilePosition(4, 3), True))
            self.small.append(Location(self.top_left + TilePosition(6, 3), True))
            self.small.append(Location(self.top_left + TilePosition(10, 0), True))
            self.small.append(Location(self.top_left + TilePosition(10, 2), True))
            self.small.append(Location(self.top_left + TilePosition(10, 4), True))
        else:
            self.small.append(Location(self.top_left + TilePosition(7, 2)))
            self.small.append(Location(self.top_left + TilePosition(7, 0)))
            self.small.append(Location(self.top_left + TilePosition(7, 4)))
            self.medium.append(Location(self.top_left))
            self.medium.append(Location(self.top_left + TilePosition(0, 2)))
            self.medium.append(Location(self.top_left + TilePosition(0, 4)))
            self.large.append(Location(self.top_left + TilePosition(3, 0)))
            self.large.append(Location(self.top_left + TilePosition(3, 3)))
            self.large.append(Location(self.top_left + TilePosition(9, 0)))
            self.large.append(Location(self.top_left + TilePosition(9, 3)))
            self.medium.append(Location(self.top_left + TilePosition(4, 1), True))
            self.medium.append(Location(self.top_left + TilePosition(4, 3), True))
            self.medium.append(Location(self.top_left + TilePosition(9, 1), True))
            self.medium.append(Location(self.top_left + TilePosition(9, 3), True))
            self.small.append(Location(self.top_left + TilePosition(1, 0), True))
            self.small.append(Location(self.top_left + TilePosition(1, 2), True))
            self.small.append(Location(self.top_left + TilePosition(1, 4), True))
            self.small.append(Location(self.top_left + TilePosition(3, 1), True))
            self.small.append(Location(self.top_left + TilePosition(5, 1), True))
            self.small.append(Location(self.top_left + TilePosition(3, 3), True))
            self.small.append(Location(self.top_left + TilePosition(5, 3), True))
            self.small.append(Location(self.top_left + TilePosition(9, 1), True))
            self.small.append(Location(self.top_left + TilePosition(11, 1), True))
            self.small.append(Location(self.top_left + TilePosition(9, 3), True))
            self.small.append(Location(self.top_left + TilePosition(11, 3), True))
