"""Generated by tools/gen_blocks.py from Stardust's Builder/Blocks/4x8.h; do not edit."""

from __future__ import annotations

from bwapi import TilePosition
from stardust.builder.block import Block, Location


class Block4x8(Block):
    def width(self) -> int:
        return 4

    def height(self) -> int:
        return 8

    def allow_left_edge(self) -> bool:
        return False

    def allow_right_edge(self) -> bool:
        return False

    def try_create(self, tile: TilePosition, tile_availability: list[int]) -> Block | None:
        if self.place(tile, tile_availability):
            return Block4x8(tile, tile + TilePosition(0, 3))
        return None

    def place_locations(self) -> None:
        self.small.append(Location(self.top_left + TilePosition(0, 3)))
        self.small.append(Location(self.top_left + TilePosition(2, 3)))
        self.large.append(Location(self.top_left))
        self.large.append(Location(self.top_left + TilePosition(0, 5)))
        self.medium.append(Location(self.top_left + TilePosition(0, 1), True))
        self.medium.append(Location(self.top_left + TilePosition(0, 5), True))
        self.small.append(Location(self.top_left + TilePosition(0, 1), True))
        self.small.append(Location(self.top_left + TilePosition(2, 1), True))
        self.small.append(Location(self.top_left + TilePosition(0, 5), True))
        self.small.append(Location(self.top_left + TilePosition(2, 5), True))
