"""Generated by tools/gen_blocks.py from Stardust's Builder/Blocks/8x2.h; do not edit."""

from __future__ import annotations

from bwapi import TilePosition
from stardust.builder.block import Block, Location


class Block8x2(Block):
    def width(self) -> int:
        return 8

    def height(self) -> int:
        return 2

    def try_create(self, tile: TilePosition, tile_availability: list[int]) -> Block | None:
        if self.place(tile, tile_availability):
            return Block8x2(tile, tile + TilePosition(3, 0))
        return None

    def place_locations(self) -> None:
        self.small.append(Location(self.top_left + TilePosition(3, 0)))
        self.medium.append(Location(self.top_left))
        self.medium.append(Location(self.top_left + TilePosition(5, 0)))
        self.small.append(Location(self.top_left + TilePosition(1, 0), True))
        self.small.append(Location(self.top_left + TilePosition(5, 0), True))
