"""Generated by tools/gen_blocks.py from Stardust's Builder/Blocks/2x4.h; do not edit."""

from __future__ import annotations

from bwapi import TilePosition
from stardust.builder.block import Block, Location


class Block2x4(Block):
    def width(self) -> int:
        return 2

    def height(self) -> int:
        return 4

    def try_create(self, tile: TilePosition, tile_availability: list[int]) -> Block | None:
        if self.place(tile, tile_availability):
            return Block2x4(tile, tile)
        return None

    def place_locations(self) -> None:
        self.small.append(Location(self.top_left))
        self.small.append(Location(self.top_left + TilePosition(0, 2)))
