"""Generated by tools/gen_blocks.py from Stardust's Builder/Blocks/12x8.h; do not edit."""

from __future__ import annotations

import bwapi
from bwapi import TilePosition
from stardust.builder.block import Block, Location


class Block12x8(Block):
    def width(self) -> int:
        return 12

    def height(self) -> int:
        return 8

    def allow_top_edge(self) -> bool:
        return False

    def allow_left_edge(self) -> bool:
        return False

    def allow_right_edge(self) -> bool:
        return False

    def allow_corner(self) -> bool:
        return False

    def try_create(self, tile: TilePosition, tile_availability: list[int]) -> Block | None:
        if self.place(tile, tile_availability):
            if self.top_left.x == 0:
                return Block12x8(tile, tile + TilePosition(4, 3))
            else:
                return Block12x8(tile, tile + TilePosition(6, 3))
        return None

    def tiles_used(self, tile: TilePosition, size: TilePosition) -> bool:
        if not super().tiles_used(tile, size):
            return False
        # When the first medium location is taken to the left, it opens up the next one
        if tile == (self.top_left + TilePosition(3, 3)) and size.x == 3 and size.y == 2:
            self.medium.append(Location(self.top_left + TilePosition(0, 3)))
            self.small.append(Location(self.top_left + TilePosition(1, 3), True))
            self.remove_used()
            return True
        # When the first medium location is taken to the right, it opens up the next one
        # Only applies when on left map edge
        if tile == (self.top_left + TilePosition(6, 3)) and size.x == 3 and size.y == 2:
            self.medium.append(Location(self.top_left + TilePosition(9, 3)))
            self.small.append(Location(self.top_left + TilePosition(9, 3), True))
            self.remove_used()
            return True
        # If the first location on the left is instead taken with a converted pylon, it opens up the next two pylons
        if tile == (self.top_left + TilePosition(4, 3)) and size.x == 2 and size.y == 2:
            self.small.append(Location(self.top_left + TilePosition(2, 3)))
            self.remove_used()
            return True
        if tile == (self.top_left + TilePosition(2, 3)) and size.x == 2 and size.y == 2:
            self.small.append(Location(self.top_left + TilePosition(0, 3)))
            self.remove_used()
            return True
        # If the first location on the right is instead taken with a converted pylon, it opens up another pylon
        if tile == (self.top_left + TilePosition(8, 3)) and size.x == 2 and size.y == 2:
            self.small.append(Location(self.top_left + TilePosition(10, 3)))
            self.remove_used()
            return True
        # If the first location on the right (left edge version) is instead taken with a converted pylon, it opens up the next two pylons
        if tile == (self.top_left + TilePosition(6, 3)) and size.x == 2 and size.y == 2:
            self.small.append(Location(self.top_left + TilePosition(8, 3)))
            self.remove_used()
            return True
        if tile == (self.top_left + TilePosition(8, 3)) and size.x == 2 and size.y == 2:
            self.small.append(Location(self.top_left + TilePosition(10, 3)))
            self.remove_used()
            return True
        return True

    def place_locations(self) -> None:
        if self.top_left.x == 0:
            self.small.append(Location(self.top_left + TilePosition(4, 3)))
            self.small.append(Location(self.top_left + TilePosition(2, 3)))
            self.small.append(Location(self.top_left + TilePosition(0, 3)))
            self.medium.append(Location(self.top_left + TilePosition(6, 3), False, False))
            self.small.append(Location(self.top_left + TilePosition(6, 3), True))
        elif self.top_left.x + 12 == bwapi.Broodwar.mapWidth():
            self.small.append(Location(self.top_left + TilePosition(6, 3)))
            self.small.append(Location(self.top_left + TilePosition(8, 3)))
            self.small.append(Location(self.top_left + TilePosition(10, 3)))
            self.medium.append(Location(self.top_left + TilePosition(3, 3), False, False))
            self.small.append(Location(self.top_left + TilePosition(4, 3), True))
        else:
            self.small.append(Location(self.top_left + TilePosition(6, 3)))
            self.medium.append(Location(self.top_left + TilePosition(3, 3), False, False))
            self.medium.append(Location(self.top_left + TilePosition(8, 3)))
            self.small.append(Location(self.top_left + TilePosition(8, 3), True))
            self.small.append(Location(self.top_left + TilePosition(4, 3), True))
        self.large.append(Location(self.top_left))
        self.large.append(Location(self.top_left + TilePosition(0, 5)))
        self.large.append(Location(self.top_left + TilePosition(4, 0)))
        self.large.append(Location(self.top_left + TilePosition(4, 5)))
        self.large.append(Location(self.top_left + TilePosition(8, 0)))
        self.large.append(Location(self.top_left + TilePosition(8, 5)))
        self.medium.append(Location(self.top_left + TilePosition(1, 1), True))
        self.medium.append(Location(self.top_left + TilePosition(1, 5), True))
        self.medium.append(Location(self.top_left + TilePosition(5, 1), True))
        self.medium.append(Location(self.top_left + TilePosition(5, 5), True))
        self.medium.append(Location(self.top_left + TilePosition(8, 1), True))
        self.medium.append(Location(self.top_left + TilePosition(8, 5), True))
        self.small.append(Location(self.top_left + TilePosition(0, 1), True))
        self.small.append(Location(self.top_left + TilePosition(2, 1), True))
        self.small.append(Location(self.top_left + TilePosition(0, 5), True))
        self.small.append(Location(self.top_left + TilePosition(2, 5), True))
        self.small.append(Location(self.top_left + TilePosition(4, 1), True))
        self.small.append(Location(self.top_left + TilePosition(6, 1), True))
        self.small.append(Location(self.top_left + TilePosition(4, 5), True))
        self.small.append(Location(self.top_left + TilePosition(6, 5), True))
        self.small.append(Location(self.top_left + TilePosition(8, 1), True))
        self.small.append(Location(self.top_left + TilePosition(10, 1), True))
        self.small.append(Location(self.top_left + TilePosition(8, 5), True))
        self.small.append(Location(self.top_left + TilePosition(10, 5), True))
