"""Generated by tools/gen_blocks.py from Stardust's Builder/Blocks/16x8.h; do not edit."""

from __future__ import annotations

from bwapi import TilePosition
from stardust.builder.block import Block, Location


class Block16x8(Block):
    def width(self) -> int:
        return 16

    def height(self) -> int:
        return 8

    def allow_top_edge(self) -> bool:
        return False

    def allow_left_edge(self) -> bool:
        return False

    def allow_right_edge(self) -> bool:
        return False

    def allow_corner(self) -> bool:
        return False

    def try_create(self, tile: TilePosition, tile_availability: list[int]) -> Block | None:
        if self.place(tile, tile_availability):
            return Block16x8(tile, tile + TilePosition(8, 3))
        return None

    def tiles_used(self, tile: TilePosition, size: TilePosition) -> bool:
        if not super().tiles_used(tile, size):
            return False
        # When the first medium location is taken to the right, it opens up the next one
        if tile == (self.top_left + TilePosition(10, 3)) and size.x == 3 and size.y == 2:
            self.medium.append(Location(self.top_left + TilePosition(13, 3)))
            self.small.append(Location(self.top_left + TilePosition(13, 3), True))
            self.remove_used()
            return True
        # If the first location on the right is instead taken with a converted pylon, it opens up two more pylons
        if tile == (self.top_left + TilePosition(10, 3)) and size.x == 2 and size.y == 2:
            self.small.append(Location(self.top_left + TilePosition(12, 3)))
            self.remove_used()
            return True
        if tile == (self.top_left + TilePosition(12, 3)) and size.x == 2 and size.y == 2:
            self.small.append(Location(self.top_left + TilePosition(14, 3)))
            self.remove_used()
            return True
        # When the left pylon is taken, it opens up the first medium location to the left
        if tile == (self.top_left + TilePosition(6, 3)) and size.x == 2 and size.y == 2:
            self.medium.append(Location(self.top_left + TilePosition(3, 3), False, False))
            self.small.append(Location(self.top_left + TilePosition(4, 3), True))
            self.remove_used()
            return True
        # If the first medium location to the left is taken by a converted pylon, it opens up two more pylons
        if tile == (self.top_left + TilePosition(4, 4)) and size.x == 2 and size.y == 2:
            self.small.append(Location(self.top_left + TilePosition(2, 3)))
            self.remove_used()
            return True
        if tile == (self.top_left + TilePosition(2, 3)) and size.x == 2 and size.y == 2:
            self.small.append(Location(self.top_left + TilePosition(0, 3)))
            self.remove_used()
            return True
        # When the first medium location to the left is taken, it opens up the last medium location to the left
        if tile == (self.top_left + TilePosition(3, 3)) and size.x == 3 and size.y == 2:
            self.medium.append(Location(self.top_left + TilePosition(0, 3)))
            self.remove_used()
            return True
        return True

    def place_locations(self) -> None:
        self.small.append(Location(self.top_left + TilePosition(8, 3)))
        self.small.append(Location(self.top_left + TilePosition(6, 3)))
        self.medium.append(Location(self.top_left + TilePosition(10, 3), False, False))
        self.small.append(Location(self.top_left + TilePosition(10, 3), True))
        self.large.append(Location(self.top_left))
        self.large.append(Location(self.top_left + TilePosition(0, 5)))
        self.large.append(Location(self.top_left + TilePosition(4, 0)))
        self.large.append(Location(self.top_left + TilePosition(4, 5)))
        self.large.append(Location(self.top_left + TilePosition(8, 0)))
        self.large.append(Location(self.top_left + TilePosition(8, 5)))
        self.large.append(Location(self.top_left + TilePosition(12, 0)))
        self.large.append(Location(self.top_left + TilePosition(12, 5)))
        self.medium.append(Location(self.top_left + TilePosition(1, 1), True))
        self.medium.append(Location(self.top_left + TilePosition(1, 5), True))
        self.medium.append(Location(self.top_left + TilePosition(5, 1), True))
        self.medium.append(Location(self.top_left + TilePosition(5, 5), True))
        self.medium.append(Location(self.top_left + TilePosition(8, 1), True))
        self.medium.append(Location(self.top_left + TilePosition(8, 5), True))
        self.medium.append(Location(self.top_left + TilePosition(12, 1), True))
        self.medium.append(Location(self.top_left + TilePosition(12, 5), True))
        self.small.append(Location(self.top_left + TilePosition(0, 1), True))
        self.small.append(Location(self.top_left + TilePosition(2, 1), True))
        self.small.append(Location(self.top_left + TilePosition(0, 5), True))
        self.small.append(Location(self.top_left + TilePosition(2, 5), True))
        self.small.append(Location(self.top_left + TilePosition(4, 1), True))
        self.small.append(Location(self.top_left + TilePosition(6, 1), True))
        self.small.append(Location(self.top_left + TilePosition(4, 5), True))
        self.small.append(Location(self.top_left + TilePosition(6, 5), True))
        self.small.append(Location(self.top_left + TilePosition(8, 1), True))
        self.small.append(Location(self.top_left + TilePosition(10, 1), True))
        self.small.append(Location(self.top_left + TilePosition(8, 5), True))
        self.small.append(Location(self.top_left + TilePosition(10, 5), True))
        self.small.append(Location(self.top_left + TilePosition(12, 1), True))
        self.small.append(Location(self.top_left + TilePosition(14, 1), True))
        self.small.append(Location(self.top_left + TilePosition(12, 5), True))
        self.small.append(Location(self.top_left + TilePosition(14, 5), True))
