"""Generated by tools/gen_blocks.py from Stardust's Builder/Blocks/10x6.h; do not edit."""

from __future__ import annotations

from bwapi import TilePosition
from stardust.builder.block import Block, Location


class Block10x6(Block):
    def width(self) -> int:
        return 10

    def height(self) -> int:
        return 6

    def allow_corner(self) -> bool:
        return False

    def try_create(self, tile: TilePosition, tile_availability: list[int]) -> Block | None:
        if self.place(tile, tile_availability):
            return Block10x6(tile, tile + TilePosition(4, 2))
        return None

    def place_locations(self) -> None:
        self.small.append(Location(self.top_left + TilePosition(4, 2)))
        self.small.append(Location(self.top_left + TilePosition(4, 0)))
        self.small.append(Location(self.top_left + TilePosition(4, 4)))
        self.large.append(Location(self.top_left))
        self.large.append(Location(self.top_left + TilePosition(0, 3)))
        self.large.append(Location(self.top_left + TilePosition(6, 0)))
        self.large.append(Location(self.top_left + TilePosition(6, 3)))
        self.medium.append(Location(self.top_left + TilePosition(1, 1), True))
        self.medium.append(Location(self.top_left + TilePosition(1, 3), True))
        self.medium.append(Location(self.top_left + TilePosition(6, 1), True))
        self.medium.append(Location(self.top_left + TilePosition(6, 3), True))
        self.small.append(Location(self.top_left + TilePosition(0, 1), True))
        self.small.append(Location(self.top_left + TilePosition(2, 1), True))
        self.small.append(Location(self.top_left + TilePosition(0, 3), True))
        self.small.append(Location(self.top_left + TilePosition(2, 3), True))
        self.small.append(Location(self.top_left + TilePosition(6, 1), True))
        self.small.append(Location(self.top_left + TilePosition(8, 1), True))
        self.small.append(Location(self.top_left + TilePosition(6, 3), True))
        self.small.append(Location(self.top_left + TilePosition(8, 3), True))
