"""Generated by tools/gen_blocks.py from Stardust's Builder/Blocks/8x5.h; do not edit."""

from __future__ import annotations

from bwapi import TilePosition
from stardust.builder.block import Block, Location


class Block8x5(Block):
    def width(self) -> int:
        return 8

    def height(self) -> int:
        return 5

    def allow_top_edge(self) -> bool:
        return False

    def allow_corner(self) -> bool:
        return False

    def try_create(self, tile: TilePosition, tile_availability: list[int]) -> Block | None:
        if self.place(tile, tile_availability):
            return Block8x5(tile, tile)
        return None

    def tiles_used(self, tile: TilePosition, size: TilePosition) -> bool:
        if not super().tiles_used(tile, size):
            return False
        # When the right converted pylon is taken, it opens up two more pylons
        if tile == (self.top_left + TilePosition(2, 0)) and size.x == 2 and size.y == 2:
            self.small.append(Location(self.top_left + TilePosition(4, 0), True))
            self.small.append(Location(self.top_left + TilePosition(6, 0), True))
            self.remove_used()
            return True
        return True

    def place_locations(self) -> None:
        self.small.append(Location(self.top_left))
        self.medium.append(Location(self.top_left + TilePosition(2, 0)))
        self.medium.append(Location(self.top_left + TilePosition(5, 0)))
        self.large.append(Location(self.top_left + TilePosition(0, 2)))
        self.large.append(Location(self.top_left + TilePosition(4, 2)))
        self.medium.append(Location(self.top_left + TilePosition(0, 2), True))
        self.medium.append(Location(self.top_left + TilePosition(4, 2), True))
        self.small.append(Location(self.top_left + TilePosition(2, 0), True))
        self.small.append(Location(self.top_left + TilePosition(0, 2), True))
        self.small.append(Location(self.top_left + TilePosition(2, 2), True))
        self.small.append(Location(self.top_left + TilePosition(4, 2), True))
        self.small.append(Location(self.top_left + TilePosition(6, 2), True))
