"""Generated by tools/gen_blocks.py from Stardust's Builder/Blocks/18x6.h; do not edit."""

from __future__ import annotations

from bwapi import TilePosition
from stardust.builder.block import Block, Location


class Block18x6(Block):
    def width(self) -> int:
        return 18

    def height(self) -> int:
        return 6

    def allow_top_edge(self) -> bool:
        return False

    def allow_corner(self) -> bool:
        return False

    def try_create(self, tile: TilePosition, tile_availability: list[int]) -> Block | None:
        if self.place(tile, tile_availability):
            return Block18x6(tile, tile + TilePosition(8, 2))
        return None

    def place_locations(self) -> None:
        self.small.append(Location(self.top_left + TilePosition(8, 2)))
        self.small.append(Location(self.top_left + TilePosition(8, 0)))
        self.small.append(Location(self.top_left + TilePosition(8, 4)))
        self.large.append(Location(self.top_left))
        self.large.append(Location(self.top_left + TilePosition(0, 3)))
        self.large.append(Location(self.top_left + TilePosition(4, 0)))
        self.large.append(Location(self.top_left + TilePosition(4, 3)))
        self.large.append(Location(self.top_left + TilePosition(10, 0)))
        self.large.append(Location(self.top_left + TilePosition(10, 3)))
        self.large.append(Location(self.top_left + TilePosition(14, 0)))
        self.large.append(Location(self.top_left + TilePosition(14, 3)))
        self.medium.append(Location(self.top_left + TilePosition(1, 1), True))
        self.medium.append(Location(self.top_left + TilePosition(1, 3), True))
        self.medium.append(Location(self.top_left + TilePosition(5, 1), True))
        self.medium.append(Location(self.top_left + TilePosition(5, 3), True))
        self.medium.append(Location(self.top_left + TilePosition(10, 1), True))
        self.medium.append(Location(self.top_left + TilePosition(10, 3), True))
        self.medium.append(Location(self.top_left + TilePosition(14, 1), True))
        self.medium.append(Location(self.top_left + TilePosition(14, 3), True))
        self.small.append(Location(self.top_left + TilePosition(0, 1), True))
        self.small.append(Location(self.top_left + TilePosition(2, 1), True))
        self.small.append(Location(self.top_left + TilePosition(0, 3), True))
        self.small.append(Location(self.top_left + TilePosition(2, 3), True))
        self.small.append(Location(self.top_left + TilePosition(4, 1), True))
        self.small.append(Location(self.top_left + TilePosition(6, 1), True))
        self.small.append(Location(self.top_left + TilePosition(4, 3), True))
        self.small.append(Location(self.top_left + TilePosition(6, 3), True))
        self.small.append(Location(self.top_left + TilePosition(10, 1), True))
        self.small.append(Location(self.top_left + TilePosition(12, 1), True))
        self.small.append(Location(self.top_left + TilePosition(10, 3), True))
        self.small.append(Location(self.top_left + TilePosition(12, 3), True))
        self.small.append(Location(self.top_left + TilePosition(14, 1), True))
        self.small.append(Location(self.top_left + TilePosition(16, 1), True))
        self.small.append(Location(self.top_left + TilePosition(14, 3), True))
        self.small.append(Location(self.top_left + TilePosition(16, 3), True))
