"""Generated by tools/gen_blocks.py from Stardust's Builder/Blocks/14x3.h; do not edit."""

from __future__ import annotations

from bwapi import TilePosition
from stardust.builder.block import Block, Location


class Block14x3(Block):
    def width(self) -> int:
        return 14

    def height(self) -> int:
        return 3

    def try_create(self, tile: TilePosition, tile_availability: list[int]) -> Block | None:
        if self.place(tile, tile_availability):
            return Block14x3(tile, tile + TilePosition(8, 0))
        return None

    def place_locations(self) -> None:
        self.small.append(Location(self.top_left + TilePosition(8, 0)))
        self.large.append(Location(self.top_left))
        self.large.append(Location(self.top_left + TilePosition(4, 0)))
        self.large.append(Location(self.top_left + TilePosition(10, 0)))
        self.medium.append(Location(self.top_left + TilePosition(1, 0), True))
        self.medium.append(Location(self.top_left + TilePosition(5, 0), True))
        self.medium.append(Location(self.top_left + TilePosition(10, 0), True))
        self.small.append(Location(self.top_left + TilePosition(0, 0), True))
        self.small.append(Location(self.top_left + TilePosition(2, 0), True))
        self.small.append(Location(self.top_left + TilePosition(4, 0), True))
        self.small.append(Location(self.top_left + TilePosition(6, 0), True))
        self.small.append(Location(self.top_left + TilePosition(10, 0), True))
        self.small.append(Location(self.top_left + TilePosition(12, 0), True))
