"""Generated by tools/gen_blocks.py from Stardust's Builder/Blocks/StartAboveAndBelowLeft.h; do not edit."""

from __future__ import annotations

from bwapi import TilePosition
from stardust.builder.block import Block, Location


# This start block is useful in mains with a geyser on left and minerals on bottom and right, like Outsider 5 o'clock
class StartAboveAndBelowLeft(Block):
    def width(self) -> int:
        return 14

    def height(self) -> int:
        return 9

    def allow_top_edge(self) -> bool:
        return False

    def allow_left_edge(self) -> bool:
        return False

    def allow_right_edge(self) -> bool:
        return False

    def allow_corner(self) -> bool:
        return False

    def try_create(self, tile: TilePosition, tile_availability: list[int]) -> Block | None:
        # For start blocks the provided tile is the nexus
        block_tile = tile + TilePosition(-10, -2)
        # Generate block tiles
        used_tiles = [
            block_tile + TilePosition(8, 0),
            block_tile + TilePosition(9, 0),
            block_tile + TilePosition(10, 0),
            block_tile + TilePosition(8, 1),
            block_tile + TilePosition(9, 1),
            block_tile + TilePosition(10, 1),
            block_tile + TilePosition(11, 0),
            block_tile + TilePosition(12, 0),
            block_tile + TilePosition(13, 0),
            block_tile + TilePosition(11, 1),
            block_tile + TilePosition(12, 1),
            block_tile + TilePosition(13, 1),
            block_tile + TilePosition(8, 4),
            block_tile + TilePosition(9, 4),
            block_tile + TilePosition(8, 5),
            block_tile + TilePosition(9, 5),
            block_tile + TilePosition(0, 6),
            block_tile + TilePosition(1, 6),
            block_tile + TilePosition(2, 6),
            block_tile + TilePosition(3, 6),
            block_tile + TilePosition(4, 6),
            block_tile + TilePosition(5, 6),
            block_tile + TilePosition(6, 6),
            block_tile + TilePosition(7, 6),
            block_tile + TilePosition(0, 7),
            block_tile + TilePosition(1, 7),
            block_tile + TilePosition(2, 7),
            block_tile + TilePosition(3, 7),
            block_tile + TilePosition(4, 7),
            block_tile + TilePosition(5, 7),
            block_tile + TilePosition(6, 7),
            block_tile + TilePosition(7, 7),
            block_tile + TilePosition(0, 8),
            block_tile + TilePosition(1, 8),
            block_tile + TilePosition(2, 8),
            block_tile + TilePosition(3, 8),
            block_tile + TilePosition(4, 8),
            block_tile + TilePosition(5, 8),
            block_tile + TilePosition(6, 8),
            block_tile + TilePosition(7, 8),
        ]
        # Generate surrounding tiles
        border_tiles = [
            block_tile + TilePosition(14, 1),
            block_tile + TilePosition(14, 0),
            block_tile + TilePosition(14, -1),
            block_tile + TilePosition(13, -1),
            block_tile + TilePosition(12, -1),
            block_tile + TilePosition(11, -1),
            block_tile + TilePosition(10, -1),
            block_tile + TilePosition(9, -1),
            block_tile + TilePosition(8, -1),
            block_tile + TilePosition(7, -1),
            block_tile + TilePosition(7, 0),
            block_tile + TilePosition(7, 1),
            block_tile + TilePosition(7, 2),
            block_tile + TilePosition(8, 2),
            block_tile + TilePosition(9, 2),
            block_tile + TilePosition(9, 3),
            block_tile + TilePosition(8, 3),
            block_tile + TilePosition(7, 3),
            block_tile + TilePosition(7, 4),
            block_tile + TilePosition(7, 5),
            block_tile + TilePosition(6, 5),
            block_tile + TilePosition(5, 5),
            block_tile + TilePosition(4, 5),
            block_tile + TilePosition(3, 5),
            block_tile + TilePosition(2, 5),
            block_tile + TilePosition(1, 5),
            block_tile + TilePosition(0, 5),
            block_tile + TilePosition(-1, 5),
            block_tile + TilePosition(-1, 6),
            block_tile + TilePosition(-1, 7),
            block_tile + TilePosition(-1, 8),
            block_tile + TilePosition(-1, 9),
            block_tile + TilePosition(0, 9),
            block_tile + TilePosition(1, 9),
            block_tile + TilePosition(2, 9),
            block_tile + TilePosition(3, 9),
            block_tile + TilePosition(4, 9),
            block_tile + TilePosition(5, 9),
            block_tile + TilePosition(6, 9),
            block_tile + TilePosition(7, 9),
            block_tile + TilePosition(8, 9),
            block_tile + TilePosition(8, 8),
            block_tile + TilePosition(8, 7),
            block_tile + TilePosition(8, 6),
            block_tile + TilePosition(9, 6),
            block_tile + TilePosition(10, 6),
            block_tile + TilePosition(10, 5)
        ]
        if self.place_start_block(tile, used_tiles, border_tiles, tile_availability):
            return StartAboveAndBelowLeft(block_tile, block_tile + TilePosition(8, 4))
        return None

    def place_locations(self) -> None:
        self.small.append(Location(self.top_left + TilePosition(8, 4)))
        self.medium.append(Location(self.top_left + TilePosition(8, 0)))
        self.medium.append(Location(self.top_left + TilePosition(11, 0)))
        self.large.append(Location(self.top_left + TilePosition(0, 6)))
        self.large.append(Location(self.top_left + TilePosition(4, 6)))
        self.cannons.append(self.top_left + TilePosition(14, 4))
        self.cannons.append(self.top_left + TilePosition(11, 5))
        self.cannons.append(self.top_left + TilePosition(14, 1))
