"""Generated by tools/gen_blocks.py from Stardust's Builder/Blocks/StartCompactRight.h; do not edit."""

from __future__ import annotations

from bwapi import TilePosition
from stardust.builder.block import Block, Location


# This start block is useful on maps with a narrow main, e.g. La Mancha 7 o'clock
class StartCompactRight(Block):
    def width(self) -> int:
        return 8

    def height(self) -> int:
        return 7

    def allow_top_edge(self) -> bool:
        return False

    def allow_left_edge(self) -> bool:
        return False

    def allow_right_edge(self) -> bool:
        return False

    def allow_corner(self) -> bool:
        return False

    def try_create(self, tile: TilePosition, tile_availability: list[int]) -> Block | None:
        # For start blocks the provided tile is the nexus
        block_tile = tile + TilePosition(1, -1)
        # Generate block tiles
        used_tiles = [
            block_tile + TilePosition(3, 0),
            block_tile + TilePosition(4, 0),
            block_tile + TilePosition(5, 0),
            block_tile + TilePosition(6, 0),
            block_tile + TilePosition(7, 0),
            block_tile + TilePosition(3, 1),
            block_tile + TilePosition(4, 1),
            block_tile + TilePosition(5, 1),
            block_tile + TilePosition(6, 1),
            block_tile + TilePosition(7, 1),
            block_tile + TilePosition(3, 2),
            block_tile + TilePosition(4, 2),
            block_tile + TilePosition(5, 2),
            block_tile + TilePosition(6, 2),
            block_tile + TilePosition(7, 2),
            block_tile + TilePosition(3, 3),
            block_tile + TilePosition(4, 3),
            block_tile + TilePosition(5, 3),
            block_tile + TilePosition(6, 3),
            block_tile + TilePosition(7, 3),
            block_tile + TilePosition(0, 4),
            block_tile + TilePosition(1, 4),
            block_tile + TilePosition(2, 4),
            block_tile + TilePosition(3, 4),
            block_tile + TilePosition(4, 4),
            block_tile + TilePosition(5, 4),
            block_tile + TilePosition(6, 4),
            block_tile + TilePosition(7, 4),
            block_tile + TilePosition(0, 5),
            block_tile + TilePosition(1, 5),
            block_tile + TilePosition(2, 5),
            block_tile + TilePosition(3, 5),
            block_tile + TilePosition(4, 5),
            block_tile + TilePosition(5, 5),
            block_tile + TilePosition(6, 5),
            block_tile + TilePosition(7, 5),
            block_tile + TilePosition(0, 6),
            block_tile + TilePosition(1, 6),
            block_tile + TilePosition(2, 6),
            block_tile + TilePosition(3, 6),
            block_tile + TilePosition(4, 6),
            block_tile + TilePosition(5, 6),
            block_tile + TilePosition(6, 6),
            block_tile + TilePosition(7, 6)
        ]
        # Generate surrounding tiles
        border_tiles = [
            block_tile + TilePosition(3, -1),
            block_tile + TilePosition(4, -1),
            block_tile + TilePosition(5, -1),
            block_tile + TilePosition(6, -1),
            block_tile + TilePosition(7, -1),
            block_tile + TilePosition(8, -1),
            block_tile + TilePosition(8, 0),
            block_tile + TilePosition(8, 1),
            block_tile + TilePosition(8, 2),
            block_tile + TilePosition(8, 3),
            block_tile + TilePosition(8, 4),
            block_tile + TilePosition(8, 5),
            block_tile + TilePosition(8, 6),
            block_tile + TilePosition(8, 7),
            block_tile + TilePosition(7, 7),
            block_tile + TilePosition(6, 7),
            block_tile + TilePosition(5, 7),
            block_tile + TilePosition(4, 7),
            block_tile + TilePosition(3, 7),
            block_tile + TilePosition(2, 7),
            block_tile + TilePosition(1, 7),
            block_tile + TilePosition(0, 7),
            block_tile + TilePosition(-1, 7),
            block_tile + TilePosition(-1, 6),
            block_tile + TilePosition(-1, 5),
            block_tile + TilePosition(-1, 4)
        ]
        if self.place_start_block(tile, used_tiles, border_tiles, tile_availability):
            return StartCompactRight(block_tile, block_tile + TilePosition(3, 2))
        return None

    def place_locations(self) -> None:
        self.small.append(Location(self.top_left + TilePosition(3, 2)))
        self.small.append(Location(self.top_left + TilePosition(3, 0)))
        self.medium.append(Location(self.top_left + TilePosition(5, 2)))
        self.medium.append(Location(self.top_left + TilePosition(5, 0)))
        self.large.append(Location(self.top_left + TilePosition(0, 4)))
        self.large.append(Location(self.top_left + TilePosition(4, 4)))
        self.cannons.append(self.top_left + TilePosition(-3, 4))
        self.cannons.append(self.top_left + TilePosition(-3, -1))
        self.cannons.append(self.top_left + TilePosition(1, -1))
