"""Generated by tools/gen_blocks.py from Stardust's Builder/Blocks/StartTopLeftHorizontal.h; do not edit."""

from __future__ import annotations

from bwapi import TilePosition
from stardust.builder.block import Block, Location


# This start block is useful in mains with a geyser on left and minerals on right, like Tau Cross 6 o'clock
class StartTopLeftHorizontal(Block):
    def width(self) -> int:
        return 11

    def height(self) -> int:
        return 6

    def allow_top_edge(self) -> bool:
        return False

    def allow_left_edge(self) -> bool:
        return False

    def allow_right_edge(self) -> bool:
        return False

    def allow_corner(self) -> bool:
        return False

    def try_create(self, tile: TilePosition, tile_availability: list[int]) -> Block | None:
        # For start blocks the provided tile is the nexus
        block_tile = tile + TilePosition(-7, -4)
        # Generate block tiles
        used_tiles = [
            block_tile + TilePosition(0, 0),
            block_tile + TilePosition(1, 0),
            block_tile + TilePosition(2, 0),
            block_tile + TilePosition(3, 0),
            block_tile + TilePosition(4, 0),
            block_tile + TilePosition(5, 0),
            block_tile + TilePosition(6, 0),
            block_tile + TilePosition(7, 0),
            block_tile + TilePosition(8, 0),
            block_tile + TilePosition(9, 0),
            block_tile + TilePosition(10, 0),
            block_tile + TilePosition(0, 1),
            block_tile + TilePosition(1, 1),
            block_tile + TilePosition(2, 1),
            block_tile + TilePosition(3, 1),
            block_tile + TilePosition(4, 1),
            block_tile + TilePosition(5, 1),
            block_tile + TilePosition(6, 1),
            block_tile + TilePosition(7, 1),
            block_tile + TilePosition(8, 1),
            block_tile + TilePosition(9, 1),
            block_tile + TilePosition(10, 1),
            block_tile + TilePosition(0, 2),
            block_tile + TilePosition(1, 2),
            block_tile + TilePosition(2, 2),
            block_tile + TilePosition(3, 2),
            block_tile + TilePosition(4, 2),
            block_tile + TilePosition(5, 2),
            block_tile + TilePosition(6, 2),
            block_tile + TilePosition(7, 2),
            block_tile + TilePosition(8, 2),
            block_tile + TilePosition(9, 2),
            block_tile + TilePosition(10, 2),
            block_tile + TilePosition(8, 3),
            block_tile + TilePosition(9, 3),
            block_tile + TilePosition(10, 3),
            block_tile + TilePosition(5, 4),
            block_tile + TilePosition(6, 4),
            block_tile + TilePosition(5, 5),
            block_tile + TilePosition(6, 5)
        ]
        # Generate surrounding tiles
        border_tiles = [
            block_tile + TilePosition(7, 6),
            block_tile + TilePosition(5, 6),
            block_tile + TilePosition(4, 6),
            block_tile + TilePosition(4, 5),
            block_tile + TilePosition(4, 4),
            block_tile + TilePosition(7, 3),
            block_tile + TilePosition(6, 3),
            block_tile + TilePosition(5, 3),
            block_tile + TilePosition(4, 3),
            block_tile + TilePosition(3, 3),
            block_tile + TilePosition(2, 3),
            block_tile + TilePosition(1, 3),
            block_tile + TilePosition(0, 3),
            block_tile + TilePosition(-1, 3),
            block_tile + TilePosition(-1, 2),
            block_tile + TilePosition(-1, 1),
            block_tile + TilePosition(-1, 0),
            block_tile + TilePosition(-1, -1),
            block_tile + TilePosition(0, -1),
            block_tile + TilePosition(1, -1),
            block_tile + TilePosition(2, -1),
            block_tile + TilePosition(3, -1),
            block_tile + TilePosition(4, -1),
            block_tile + TilePosition(5, -1),
            block_tile + TilePosition(6, -1),
            block_tile + TilePosition(7, -1),
            block_tile + TilePosition(8, -1),
            block_tile + TilePosition(9, -1),
            block_tile + TilePosition(10, -1),
            block_tile + TilePosition(11, -1),
            block_tile + TilePosition(11, 0),
            block_tile + TilePosition(11, 1),
            block_tile + TilePosition(11, 2),
            block_tile + TilePosition(11, 3),
            block_tile + TilePosition(11, 4)
        ]
        if self.place_start_block(tile, used_tiles, border_tiles, tile_availability):
            return StartTopLeftHorizontal(block_tile, block_tile + TilePosition(5, 4))
        return None

    def place_locations(self) -> None:
        self.small.append(Location(self.top_left + TilePosition(5, 4)))
        self.medium.append(Location(self.top_left + TilePosition(8, 2)))
        self.medium.append(Location(self.top_left + TilePosition(8, 0)))
        self.large.append(Location(self.top_left + TilePosition(4, 0)))
        self.large.append(Location(self.top_left))
        self.cannons.append(self.top_left + TilePosition(10, 7))
        self.cannons.append(self.top_left + TilePosition(11, 3))
        self.cannons.append(self.top_left + TilePosition(5, 7))
