"""Generated by tools/gen_blocks.py from Stardust's Builder/Blocks/StartNormalRight.h; do not edit."""

from __future__ import annotations

import bwapi
from bwapi import TilePosition
from stardust.builder.block import Block, Location


class StartNormalRight(Block):
    def width(self) -> int:
        return 8

    def height(self) -> int:
        return 7

    def allow_top_edge(self) -> bool:
        return False

    def allow_left_edge(self) -> bool:
        return False

    def allow_right_edge(self) -> bool:
        return False

    def allow_corner(self) -> bool:
        return False

    def try_create(self, tile: TilePosition, tile_availability: list[int]) -> Block | None:
        # For start blocks the provided tile is the nexus
        block_tile = tile + TilePosition(4, -2)
        # Generate block tiles
        used_tiles: list[TilePosition] = []
        border_tiles: list[TilePosition] = []
        for tile_x in range(block_tile.x - 1, block_tile.x + 8 + 1):
            for tile_y in range(block_tile.y - 1, block_tile.y + 7 + 1):
                if tile_x < 0 or tile_y < 0 or tile_x >= bwapi.Broodwar.mapWidth() or tile_y >= bwapi.Broodwar.mapHeight():
                    return None
                if tile_x == block_tile.x - 1 or tile_y == block_tile.y - 1 or tile_x == block_tile.x + 8 or tile_y == block_tile.y + 7:
                    border_tiles.append(TilePosition(tile_x, tile_y))
                else:
                    used_tiles.append(TilePosition(tile_x, tile_y))
        if self.place_start_block(tile, used_tiles, border_tiles, tile_availability):
            return StartNormalRight(block_tile, block_tile + TilePosition(0, 2))
        return None

    def place_locations(self) -> None:
        self.small.append(Location(self.top_left + TilePosition(0, 2)))
        self.small.append(Location(self.top_left))
        self.medium.append(Location(self.top_left + TilePosition(2, 2), False, False))
        self.medium.append(Location(self.top_left + TilePosition(5, 2)))
        self.medium.append(Location(self.top_left + TilePosition(2, 0)))
        self.medium.append(Location(self.top_left + TilePosition(5, 0)))
        self.large.append(Location(self.top_left + TilePosition(0, 4)))
        self.large.append(Location(self.top_left + TilePosition(4, 4)))
        self.cannons.append(self.top_left + TilePosition(-6, 5))
        self.cannons.append(self.top_left + TilePosition(-6, 0))
        self.cannons.append(self.top_left + TilePosition(-2, 5))
        self.cannons.append(self.top_left + TilePosition(-2, 0))
