"""Generated by tools/gen_blocks.py from Stardust's Builder/Blocks/StartCompactRightVertical.h; do not edit."""

from __future__ import annotations

from bwapi import TilePosition
from stardust.builder.block import Block, Location


class StartCompactRightVertical(Block):
    def width(self) -> int:
        return 6

    def height(self) -> int:
        return 8

    def allow_top_edge(self) -> bool:
        return False

    def allow_left_edge(self) -> bool:
        return False

    def allow_right_edge(self) -> bool:
        return False

    def allow_corner(self) -> bool:
        return False

    def try_create(self, tile: TilePosition, tile_availability: list[int]) -> Block | None:
        # For start blocks the provided tile is the nexus
        block_tile = tile + TilePosition(4, -3)
        # Generate block tiles
        used_tiles = [
            block_tile + TilePosition(2, 0),
            block_tile + TilePosition(3, 0),
            block_tile + TilePosition(4, 0),
            block_tile + TilePosition(5, 0),
            block_tile + TilePosition(2, 1),
            block_tile + TilePosition(3, 1),
            block_tile + TilePosition(4, 1),
            block_tile + TilePosition(5, 1),
            block_tile + TilePosition(0, 2),
            block_tile + TilePosition(1, 2),
            block_tile + TilePosition(2, 2),
            block_tile + TilePosition(3, 2),
            block_tile + TilePosition(4, 2),
            block_tile + TilePosition(5, 2),
            block_tile + TilePosition(0, 3),
            block_tile + TilePosition(1, 3),
            block_tile + TilePosition(2, 3),
            block_tile + TilePosition(3, 3),
            block_tile + TilePosition(4, 3),
            block_tile + TilePosition(5, 3),
            block_tile + TilePosition(0, 4),
            block_tile + TilePosition(1, 4),
            block_tile + TilePosition(2, 4),
            block_tile + TilePosition(3, 4),
            block_tile + TilePosition(4, 4),
            block_tile + TilePosition(5, 4),
            block_tile + TilePosition(0, 5),
            block_tile + TilePosition(1, 5),
            block_tile + TilePosition(2, 5),
            block_tile + TilePosition(3, 5),
            block_tile + TilePosition(4, 5),
            block_tile + TilePosition(5, 5),
            block_tile + TilePosition(0, 6),
            block_tile + TilePosition(1, 6),
            block_tile + TilePosition(2, 6),
            block_tile + TilePosition(3, 6),
            block_tile + TilePosition(4, 6),
            block_tile + TilePosition(5, 6),
            block_tile + TilePosition(0, 7),
            block_tile + TilePosition(1, 7),
            block_tile + TilePosition(2, 7),
            block_tile + TilePosition(3, 7),
            block_tile + TilePosition(4, 7),
            block_tile + TilePosition(5, 7)
        ]
        # Generate surrounding tiles
        border_tiles = [
            block_tile + TilePosition(-1, 2),
            block_tile + TilePosition(-1, 1),
            block_tile + TilePosition(0, 1),
            block_tile + TilePosition(1, 1),
            block_tile + TilePosition(1, 0),
            block_tile + TilePosition(1, -1),
            block_tile + TilePosition(2, -1),
            block_tile + TilePosition(3, -1),
            block_tile + TilePosition(4, -1),
            block_tile + TilePosition(5, -1),
            block_tile + TilePosition(6, -1),
            block_tile + TilePosition(6, 0),
            block_tile + TilePosition(6, 1),
            block_tile + TilePosition(6, 2),
            block_tile + TilePosition(6, 3),
            block_tile + TilePosition(6, 4),
            block_tile + TilePosition(6, 5),
            block_tile + TilePosition(6, 6),
            block_tile + TilePosition(6, 7),
            block_tile + TilePosition(6, 8),
            block_tile + TilePosition(6, 7),
            block_tile + TilePosition(6, 6),
            block_tile + TilePosition(6, 5),
            block_tile + TilePosition(6, 4),
            block_tile + TilePosition(6, 3),
            block_tile + TilePosition(6, 2),
            block_tile + TilePosition(6, 1),
            block_tile + TilePosition(6, 0),
            block_tile + TilePosition(6, -1),
            block_tile + TilePosition(5, -1),
            block_tile + TilePosition(4, -1)
        ]
        if self.place_start_block(tile, used_tiles, border_tiles, tile_availability):
            return StartCompactRightVertical(block_tile, block_tile + TilePosition(0, 4))
        return None

    def place_locations(self) -> None:
        self.small.append(Location(self.top_left + TilePosition(0, 4)))
        self.small.append(Location(self.top_left + TilePosition(0, 2)))
        self.medium.append(Location(self.top_left + TilePosition(0, 6)))
        self.medium.append(Location(self.top_left + TilePosition(3, 6)))
        self.large.append(Location(self.top_left + TilePosition(2, 0)))
        self.large.append(Location(self.top_left + TilePosition(2, 3)))
        self.cannons.append(self.top_left + TilePosition(-6, 6))
        self.cannons.append(self.top_left + TilePosition(-6, 1))
        self.cannons.append(self.top_left + TilePosition(-2, 6))
        self.cannons.append(self.top_left + TilePosition(-2, 1))
