"""Generates python/stardust/builder/blocks/*.py from Stardust's block headers (src/Builder/Blocks/*.h).

The block headers are tables of build locations with a little control flow, written in a uniform style, so they are
translated line by line rather than by hand.

    .venv/bin/python tools/gen_blocks.py .reference/Stardust/src/Builder/Blocks python/stardust/builder/blocks
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

TP = r"BWAPI::TilePosition\((-?\d+), (-?\d+)\)"


def module_name(header: Path) -> str:
    stem = header.stem
    if re.fullmatch(r"\d+x\d+", stem):
        return f"block_{stem}"
    return re.sub(r"(?<!^)(?=[A-Z])", "_", stem).lower()


def expr(text: str) -> str:
    """Translates a C++ expression."""
    text = re.sub(TP, r"TilePosition(\1, \2)", text)
    text = text.replace("BWAPI::Broodwar->mapWidth()", "bwapi.Broodwar.mapWidth()")
    text = text.replace("BWAPI::Broodwar->mapHeight()", "bwapi.Broodwar.mapHeight()")
    text = re.sub(r"\btopLeft\b", "self.top_left", text)
    text = re.sub(r"\bblockTile\b", "block_tile", text)
    text = re.sub(r"\btileX\b", "tile_x", text)
    text = re.sub(r"\btileY\b", "tile_y", text)
    text = text.replace("&&", "and").replace("||", "or")
    text = re.sub(r"!(?!=)", "not ", text)
    text = text.replace("true", "True").replace("false", "False")
    return text.strip()


def strip_parens(text: str) -> str:
    text = text.strip()
    assert text.startswith("(") and text.endswith(")"), text
    return text[1:-1]


class Translator:
    def __init__(self, source: str, name: str) -> None:
        self.lines = source.splitlines()
        self.name = name
        self.out: list[str] = []
        self.class_name = ""
        self.indent = 0
        self.pending_block = False  # a statement that opens a Python block was emitted; next "{" just confirms it
        self.brace_stack: list[bool] = []  # whether each open brace opened a Python block
        self.in_list: str | None = None
        self.member = False  # inside a class member function

    def emit(self, line: str) -> None:
        self.out.append(("    " * self.indent + line) if line else "")

    def translate(self) -> str:
        header = [
            f'"""Generated by tools/gen_blocks.py from Stardust\'s Builder/Blocks/{self.name}.h; do not edit."""',
            "",
            "from __future__ import annotations",
            "",
            "import bwapi",
            "from bwapi import TilePosition",
            "from stardust.builder.block import Block, Location",
            "",
        ]
        i = 0
        while i < len(self.lines):
            line = self.lines[i].strip()
            # Join a constructor declaration wrapped over two lines
            if "BWAPI::TilePosition topLeft," in line and "placeLocations" not in line:
                i += 1
                line += " " + self.lines[i].strip()
            self.line(line)
            i += 1
        body = "\n".join(header + [""] + self.out).rstrip() + "\n"
        body = re.sub(r"\n\n\n+(    def )", r"\n\n\1", body)
        if "bwapi.Broodwar" not in body:
            body = body.replace("import bwapi\n", "")
        return body

    def open_block(self, statement: str) -> None:
        self.emit(statement)
        self.pending_block = True

    def line(self, line: str) -> None:
        if not line or line.startswith("#include") or line in ("public:", "protected:"):
            return

        if line.startswith("//"):
            self.emit("# " + line[2:].strip())
            return

        if self.in_list is not None:
            if line.startswith("};"):
                self.indent -= 1
                self.emit("]")
                self.in_list = None
            else:
                self.emit(expr(line))
            return

        if line == "{":
            self.brace_stack.append(self.pending_block)
            if self.pending_block:
                self.indent += 1
            self.pending_block = False
            return
        if line in ("}", "};"):
            if self.brace_stack.pop():
                self.indent -= 1
                if self.indent == 1:
                    self.emit("")
            return

        m = re.fullmatch(r"class (\w+) : public Block", line)
        if m:
            self.class_name = m.group(1)
            self.open_block(f"class {self.class_name}(Block):")
            return

        # Constructor: nothing to do, Block.__init__ calls place_locations
        if re.match(r"(explicit )?\w+\(BWAPI::TilePosition topLeft, BWAPI::TilePosition powerPylon\)", line):
            return

        m = re.fullmatch(r"\[\[nodiscard\]\] (int|bool) (\w+)\(\) const override \{ return (\w+); \}", line)
        if m:
            name = {"width": "width", "height": "height", "allowTopEdge": "allow_top_edge",
                    "allowLeftEdge": "allow_left_edge", "allowRightEdge": "allow_right_edge",
                    "allowCorner": "allow_corner"}[m.group(2)]
            self.emit(f"def {name}(self) -> {m.group(1)}:")
            self.emit(f"    return {expr(m.group(3))}")
            self.emit("")
            return

        if line == ("std::shared_ptr<Block> tryCreate(BWAPI::TilePosition tile, "
                    "std::vector<unsigned int> &tileAvailability) override"):
            self.open_block("def try_create(self, tile: TilePosition, tile_availability: list[int]) -> Block | None:")
            return
        if line == "bool tilesUsed(BWAPI::TilePosition tile, BWAPI::TilePosition size) override":
            self.open_block("def tiles_used(self, tile: TilePosition, size: TilePosition) -> bool:")
            return
        if line == "void placeLocations() override":
            self.open_block("def place_locations(self) -> None:")
            return

        if line == "if (place(tile, tileAvailability))":
            self.open_block("if self.place(tile, tile_availability):")
            return
        if line == "if (placeStartBlock(tile, usedTiles, borderTiles, tileAvailability))":
            self.open_block("if self.place_start_block(tile, used_tiles, border_tiles, tile_availability):")
            return
        if line == "if (!Block::tilesUsed(tile, size)) return false;":
            self.emit("if not super().tiles_used(tile, size):")
            self.emit("    return False")
            return

        m = re.fullmatch(r"return std::make_shared<(\w+)>\((\w+), (.*)\);", line)
        if m:
            self.emit(f"return {m.group(1)}({expr(m.group(2))}, {expr(m.group(3))})")
            return
        if line == "return nullptr;":
            self.emit("return None")
            return
        if line in ("return true;", "return false;"):
            self.emit(f"return {expr(line[7:-1])}")
            return
        if line == "removeUsed();":
            self.emit("self.remove_used()")
            return

        m = re.fullmatch(r"auto blockTile = (.*);", line)
        if m:
            self.emit(f"block_tile = {expr(m.group(1))}")
            return
        m = re.fullmatch(r"std::vector<BWAPI::TilePosition> (usedTiles|borderTiles)( = \{)?;?", line)
        if m:
            name = "used_tiles" if m.group(1) == "usedTiles" else "border_tiles"
            if m.group(2):
                self.emit(f"{name} = [")
                self.indent += 1
                self.in_list = name
            else:
                self.emit(f"{name}: list[TilePosition] = []")
            return
        m = re.fullmatch(r"(usedTiles|borderTiles)\.emplace_back\(tileX, tileY\);", line)
        if m:
            name = "used_tiles" if m.group(1) == "usedTiles" else "border_tiles"
            self.emit(f"{name}.append(TilePosition(tile_x, tile_y))")
            return

        m = re.fullmatch(r"for \(int (tileX|tileY) = (.*); \1 <= (.*); \1\+\+\)", line)
        if m:
            self.open_block(f"for {expr(m.group(1))} in range({expr(m.group(2))}, {expr(m.group(3))} + 1):")
            return

        m = re.fullmatch(r"(else if|if) (\(.*\))( return nullptr;)?", line)
        if m:
            keyword = "elif" if m.group(1) == "else if" else "if"
            condition = expr(strip_parens(m.group(2)))
            if m.group(3):
                self.emit(f"{keyword} {condition}:")
                self.emit("    return None")
            else:
                self.open_block(f"{keyword} {condition}:")
            return
        if line == "else":
            self.open_block("else:")
            return

        m = re.fullmatch(r"(small|medium|large|cannons)\.emplace_back\((.*)\);", line)
        if m:
            container, args = m.group(1), m.group(2)
            if container == "cannons":
                self.emit(f"self.cannons.append({expr(args)})")
                return
            parts = [part.strip() for part in re.split(r",(?![^(]*\))", args)]
            self.emit(f"self.{container}.append(Location({', '.join(expr(part) for part in parts)}))")
            return

        raise ValueError(f"{self.name}: cannot translate: {line}")


def main() -> None:
    source_dir = Path(sys.argv[1])
    out_dir = Path(sys.argv[2])
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "__init__.py").write_text('"""Block templates (src/Builder/Blocks), generated by tools/gen_blocks.py."""\n')
    for header in sorted(source_dir.glob("*.h")):
        python = Translator(header.read_text(), header.stem).translate()
        (out_dir / f"{module_name(header)}.py").write_text(python)
        print(f"{header.name} -> {module_name(header)}.py")


if __name__ == "__main__":
    main()
